name: Deploy to EC2

on:
  push:
    branches:
      - main  # Menjalankan workflow saat ada commit ke branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub Actions akan menjalankan job di Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Menarik kode dari GitHub

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH key yang digunakan untuk akses EC2

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@3.107.70.158 'cd /var/www/html && git pull origin main'
